apiVersion: apps/v1
kind: Deployment
metadata:
  name: postic-frontend
  namespace: postic
  labels:
    app: postic-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postic-frontend
  template:
    metadata:
      labels:
        app: postic-frontend
    spec:
      containers:
      - name: frontend
        image: kristinabu/postic-frontend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
