apiVersion: v1
kind: Service
metadata:
  name: postic-frontend-service
  namespace: postic
  labels:
    app: postic-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: postic-frontend
